### ISSUE TITLE
Some feedback for improvement

### ISSUE THREAD

**Issue by silverwind** [DavidAnson/markdownlint-cli2#145]
I tried this over the other CLI. It is indeed faster, but there are a few things I dislike:

- It's not silent on success, still prints version, finding, etc. I think a good CLI is silent on success. Exisiting output could be moved to a `--verbose` flag.
- Passing a folder does not recurse into it. I'm used to just pass folders to tools like eslint, while this module supports globs only. Making folder work would require the CLI to know about the extensions like `.md`, though. Eslint has a `--ext` option for this.
- Consider unlocking the `markdownlint` dependency which is currently out of date, or just push new releases on both repos at the same time.

**Comment by DavidAnson** [comment]
For the first, you can set `noProgress` to turn off most of the default status output on `stdout`(except the version banner which is very helpful for troubleshooting).

For the second, directories should already be expanded as "**":
<https://github.com/DavidAnson/markdownlint-cli2/blob/e3c981ce9ab04c82884e2bb074e13f0ad755a63d/markdownlint-cli2.js#L441>. Adding another option that is redundant with glob syntax is not in keeping with my general attempt to keep things simple and rely on glob syntax.

All dependency versions are specified exactly because doing otherwise results in inconsistent behavior and surprises in CI, etc.. As a semver-breaking change, the new version of the library wouldn't be picked up by standard loose versioning. The release process is outlined here: https://github.com/DavidAnson/markdownlint/blob/main/doc/ReleaseProcess.md

**Comment by silverwind** [comment]
I see. Well I'll keep using `markdownlint-cli` then, it solves all the issues and seems quicker to update as well.
