### ISSUE TITLE
Update dependencies and consider not pinning them

### ISSUE THREAD

**Issue by XhmikosR** [DavidAnson/markdownlint-cli2#154]
The way things are right now, consumers cannot get any fixes without a new version here :/

Let alone that the deps cannot be properly deduped in some cases.

**Comment by DavidAnson** [comment]
I should maybe write this down somewhere since it comes up periodically. What I said before is:

> All dependency versions are specified exactly because doing otherwise results in inconsistent behavior and surprises in CI, etc..

I stand by that. (I realize transitive dependencies may still be unreliable, but I can only change what I can change.)

Dependency versioning for this package is managed by Dependabot, and I have it configured to run daily for the “next” branch. That branch should always be up to date, but I do not release a new version of the package every time a dependency changes because that happens so frequently.

If there is an especially notable dependency update or a security issue, I will usually try to release. I don’t know of anything right now to justify that, but I am happy to discuss if folks feel otherwise.

If you know of package manager bugs preventing correct de-duplication, please open an issue for them. If you want to forcibly override a dependency version, some package managers support that. Example from yarn: <https://classic.yarnpkg.com/en/docs/selective-version-resolutions/>

**Comment by DavidAnson** [comment]
Yes, thank you! I'm not sure this deserves an alert because unhandled exceptions are pretty much always possible. They are already caught and handled here, so I doubt anyone would even notice aside from the corrupt YAML file not being used.

**Comment by DavidAnson** [comment]
FYI, I was going to publish new releases tonight, but didn't get the chance. Tomorrow, probably.

**Comment by DavidAnson** [comment]
Fixed in v0.7.1

**Comment by DavidAnson** [comment]
@XhmikosR FYI that a bunch of projects likely broke this afternoon due to loose versioning allowing a patch-level breaking change into their dependency chain: <https://github.com/isaacs/jackspeak/issues/4>. As a maintainer, I'd rather not spend my evenings tracking stuff like this down and strict versioning of my own dependencies is the best way I know of to protect myself.
