### ISSUE TITLE
markdownlint-cli2 ignores .markdownlint.yaml

### ISSUE THREAD

**Issue by nex3** [DavidAnson/markdownlint-cli2#193]
[Here's a minimal reproduction](https://gist.github.com/nex3/53b4add835a286161f308910c90fbe59). To reproduce:

```shellsession
$ git clone https://gist.github.com/53b4add835a286161f308910c90fbe59.git
$ npm install
$ npx markdownlint-cli2
markdownlint-cli2 v0.8.1 (markdownlint v0.29.0)
https://github.com/DavidAnson/markdownlint-cli2

Syntax: markdownlint-cli2 glob0 [glob1] [...] [globN] [--config file] [--fix]

Glob expressions (from the globby library):
- * matches any number of characters, but not /
- ? matches a single character, but not /
- ** matches any number of characters, including /
- {} allows for a comma-separated list of "or" expressions
- ! or # at the beginning of a pattern negate the match
- : at the beginning identifies a literal file path

Dot-only glob:
- The command "markdownlint-cli2 ." would lint every file in the current directory tree which is probably not intended
- Instead, it is mapped to "markdownlint-cli2 *.{md,markdown}" which lints all Markdown files in the current directory
- To lint every file in the current directory tree, the command "markdownlint-cli2 **" can be used instead

Optional parameters:
- --config  specifies the path to a configuration file to define the base configuration
- --fix     updates files to resolve fixable issues (can be overridden in configuration)

Configuration via:
- .markdownlint-cli2.jsonc
- .markdownlint-cli2.yaml
- .markdownlint-cli2.cjs or .markdownlint-cli2.mjs
- .markdownlint.jsonc or .markdownlint.json
- .markdownlint.yaml or .markdownlint.yml
- .markdownlint.cjs or .markdownlint.mjs

Cross-platform compatibility:
- UNIX and Windows shells expand globs according to different rules; quoting arguments is recommended
- Some Windows shells don't handle single-quoted (') arguments well; double-quote (") is recommended
- Shells that expand globs do not support negated patterns (!node_modules); quoting is required here
- Some UNIX shells parse exclamation (!) in double-quotes; hashtag (#) is recommended in these cases
- The path separator is forward slash (/) on all platforms; backslash (\) is automatically converted

The most compatible syntax for cross-platform support:
$ markdownlint-cli2 "**/*.md" "#node_modules"
```

I would expect the CLI to load the set of globs from the `.markdownlint.yaml` file, as documented in its output. However, it seems to be largely ignored. Even if I set an explicit glob, any rule configuration I write in `.markdownlint.yaml` is also ignored.

**Comment by DavidAnson** [comment]
There are two types of configuration file; one is a subset of the other. Yours is named `.markdownlint.yaml`, but it should be named `.markdownlint-cli2.yaml`.

The documentation has more detail about the two kinds and the various forms they can take:
https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml

**Comment by nex3** [comment]
It wasn't clear to me from the documentation that these files had different structures than one another. It would be very helpful if the CLI provided more useful error messages when one is being used in place of the other, instead of silently failing.

**Comment by DavidAnson** [comment]
I revised the documentation area "There are two kinds of configuration file (both detailed below):" recently. Each file type has its own section with a link to an example in an effort to show how things should look. If you have suggestions to improve the documentation, please let me know.

Regarding the suggestion to fail at runtime, I do not think that is applicable in this case. The file provided was valid YAML and could have been configuring a custom rule named "globs". While there wasn't one in this case, there is no guarantee or requirement that custom rules always be present. I could specifically look for probable misconfiguration based on property names, but it seems like a fair amount of code/effort that will only ever be a guess.

The current strategy is to provide documentation and samples to help people through the configuration process, though it is not perfect and I apologize for the inconvenience here.

**Comment by nex3** [comment]
But there _wasn't_ a custom rule named `globs`, and the program errored out anyway—what's the cost of adding a check to see if the configuration file looks mistaken in that case?

**Comment by DavidAnson** [comment]
But it didn't error out in this case. No globs were passed on the command line or via a configuration file, so it displayed the help text because it had nothing to do. The same thing happens in a clean directory without any configuration file at all.

Detecting this kind of mistake in general does not seem easy to me. For example, some people will use extra/unsupported property names for comments in JSON files. Erroring because they did so would be unhelpful. Similarly, someone may use the same configuration file with multiple npm/shell scripts and one of those scripts could include a custom rule that is not present in other scripts. Erroring would prevent the reuse of that configuration file.

The least annoying runtime approach I see so far would be to look specifically for the handful of properties that are supported in options files that are not supported in configuration files and then... output a warning? But this still leads to inconsistent behavior from the tool when it doesn't need to be.

Another approach would be to provide a schema for configuration files and allow the user to validate configuration against that schema. And indeed I have already done this and people who use the VS Code extension with JSON/C files should get automatic schema validation and property suggestions when editing both file types: <https://github.com/DavidAnson/vscode-markdownlint/blob/main/markdownlint-config-schema.json>. I'm not sure if YAML supports schemas like JSON, but there is another VS Code extension (not written by me) that will apply an existing JSON schema to a YAML file to offer a similar editing experience.

So far, the downsides of the approaches I've considered outweigh the value (in my mind) for what is generally a one-time (or at least rare) configuration step that produces immediate/obviously "wrong" behavior in the presence of mistakes.

**Comment by DavidAnson** [comment]
In the current release, this project now includes JSON schemas for both configuration file types: <https://github.com/DavidAnson/markdownlint-cli2/tree/main/schema>. However, because `.markdownlint.json` is open-ended, using the wrong configuration file name will not always fail validation. As I outline above, being flexible and supporting custom rules makes that hard to prevent in general.
