### ISSUE TITLE
How to use markdown it plugins

### ISSUE THREAD

**Issue by Mister-Hope** [DavidAnson/markdownlint-cli2#260]
The repo is not providing a discussion panel, so I will ask here in issue.

I write a project <https://mdit-plugins.github.io/> which contains a lot of markdown plugins, on of them is img size plugin:

```md
![Logo](https://theme-hope-assets.vuejs.press/logo.svg =200x300)

![Logo](https://theme-hope-assets.vuejs.press/logo.svg "Image title" =200x)
![Logo](https://theme-hope-assets.vuejs.press/logo.svg =x300)
```

And with the following config:

```js
// .markdownlint-cli2.mjs
import { imgSize } from "@mdit/plugin-img-size";

export default {
  config: {
    default: true,
    // ...
  },
  markdownItPlugins: [[imgSize]],
};
```

I hope that markdownlint understand the above text are 3 images, but I am still getting error:

```
markdownlint-cli2 v0.11.0 (markdownlint v0.32.1)
Finding: **/*.md !**/node_modules/** !**/__tests__/** !**/*.snippet.md
Linting: 967 file(s)
Summary: 3 error(s)
demo/md-enhance/src/demo/image-size.md:7:9 MD034/no-bare-urls Bare URL used [Context: "https://theme-hope-assets.vuej..."]
demo/md-enhance/src/demo/image-size.md:9:9 MD034/no-bare-urls Bare URL used [Context: "https://theme-hope-assets.vuej..."]
demo/md-enhance/src/demo/image-size.md:10:9 MD034/no-bare-urls Bare URL used [Context: "https://theme-hope-assets.vuej..."]
```

Some debug shows that the plugin is at least called.

![image](https://github.com/DavidAnson/markdownlint-cli2/assets/33315834/4c8a6f06-7328-4a43-a61c-8e1c4c742887)

**Comment by DavidAnson** [comment]
As more rules are migrated to use the micromark parser, the usefulness of markdown-it plugins will decrease. MD034 has already been migrated, so the parsing changes your plugin performs are not visible to it. MD034 reports the issues above because those are not valid image definitions according to the CommonMark specification. Because of how infrequently people seem to provide custom plugins, I do not currently plan to support it for the micromark parser. Therefore, I would recommend implementing custom behavior in a way that remains a valid image definition. For example, if you put the size inside quotes and made it part of the image title, that would not produce the violation you see here.

**Comment by DavidAnson** [comment]
I don't have experience with directives yet, but that may be a way to implement the above in a way that could automatically be ignored by tools that understand directive syntax. I'm looking at including the extension below by default for the micromark parser.

More info:
- https://talk.commonmark.org/t/generic-directives-plugins-syntax/444
- https://github.com/micromark/micromark-extension-directive
