### ISSUE TITLE
markdownlint-cli2-formatter-pretty: Add support for configurable colors

### ISSUE THREAD

**Issue by ltickett** [DavidAnson/markdownlint-cli2#321]
The default colors don't work too well in GitLab CI job logs https://gitlab.com/components/markdownlint/-/jobs/6830839750

<img width="706" alt="image" src="https://github.com/DavidAnson/markdownlint-cli2/assets/4687431/2a0e526c-f775-440b-b03d-6bceb7a1810c"> 

Let's add support for configuring the colors using params.

**Comment by DavidAnson** [comment]
As I recall, I based the current colors on something popular (ESLint or npm, maybe?). Rather than add config for this, I'd prefer to use a single/fixed color palette that works well on light and dark backgrounds. Or else offer a light/dark configuration setting instead of exposing every single color choice.

Alternatively, maybe you don't need to colorize in the GitLab scenario?

**Comment by ltickett** [comment]
Thanks @DavidAnson I have essentially made a copy of the formatter for now and implemented this locally for now. We do think the color helps to differentiate each part of the message.

I threw up a pull request (didn't expect such a quick response :)

I would consider a simpler approach, maybe just fixing the one color that doesn't currently render well, or offering "2 options".

**Comment by DavidAnson** [comment]
`markdownlint-cli2-formatter-pretty` version `0.0.6` uses yellow instead of gray for better contrast.

**Comment by ltickett** [comment]
Super- thanks for tweaking this @DavidAnson 🙏
