### ISSUE TITLE
Driver name for SARIF formatter

### ISSUE THREAD

**Issue by mschoettle** [DavidAnson/markdownlint-cli2#455]
I tried out the SARIF formatter to use it in GitHub Actions. It works like a charm 👍 

One thing I find odd though is that the name shows up as "markdownlint-cli2-formatter-sarif" as the tool.

Would it be possible to change this to `markdownlint-cli2` since that is the tool? Maybe `markdownlint` would be appropriate as well.

**Comment by DavidAnson** [comment]
That's the most helpful name to get more information about the output. It distinguishes it from other formatters which might behave differently. Naming it just "markdownlint" would be hard to work backwards from for someone unfamiliar with the tool. This could be a configurable name, but can you please explain more about why the name is significant?

**Comment by mschoettle** [comment]
GitHub in this case uses the name to show it as the tool that produced/detected this violation:

![image](https://github.com/user-attachments/assets/dd91160d-aeba-44aa-88c7-65f97e63e45f)

I think that this is somewhat incorrect. The formatters just format the same violations differently, right?

However, it is not a big deal. :)

**Comment by DavidAnson** [comment]
Here is what the specification says: https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790791

I find that completely unhelpful because it has examples of using both the program name and the plug-in name. :)

Looking at the way this is presented in the UI you show, I probably agree that "markdownlint-cli2" is the most accurate "tool" name.

**Comment by DavidAnson** [comment]
Fixed in `v0.0.3` of `markdownlint-cli2-formatter-sarif`.
