### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by monkey-knuckles** [DavidAnson/markdownlint-cli2#482]
I am having trouble setting up custom rules for markdownlint. Here is the situation:

1. markdownlint is installed as a vsc plugin using markdownlint-cli2 v0.17.0 (markdownlint v0.37.2)

2. I have a settings.json file with the following contents.

```markdown
    "markdownlint.config": {
        "extends": ".config/.markdownlint.jsonc" // Sets location of '.markdownlint.jsonc' config file.

    },

    "markdownlint.customRules": [".config/custom-rules/my-custom-rule.js"],
```
3. This is working absolutely fine within VSC. 
4.  When I run the command line version to test what will happen on my CI Pipeline it runs and will lint with my .markdownlint.jsonc file just fine

What I can't do is get the command line version to lint with my config file and my custom rules file.

I am fairly certain that It's just me not knowing how. But I can confirm the plugin is working the config file is working and the custom rules JS file is working. Just need to see this play out when the command is used in the terminal.

I would very much like for my ignorance to be quelled.

Thanks, Happy, holidays.

**Comment by nschonni** [comment]
`customRules` is a property of the real config file too https://github.com/DavidAnson/markdownlint/blob/v0.32.1/README.md#optionscustomrules
If you want it to be used by both Visual Studio and the CLI, it should be registered in the config file rather than `settings.json`

**Comment by DavidAnson** [comment]
What Nick suggests is what I would say as well. :) Because we are talking about configuration files, I think this link will also be useful: https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlint-cli2jsonc

Basically, you can create a configuration file like .markdownlint-cli2.jsonc and store the custom rule information there. That file will also be used by the VS Code extension. You could decide to also put the rule configuration in there, but it's fine to keep that in its own .markdownlint.json file.

As I understand your scenario, you could get away with having a single .markdownlint-cli2.jsonc file in the root of your project and no other configuration will be needed because it will be picked up automatically by both tools.

Good luck!

**Comment by monkey-knuckles** [comment]
I had an inkling that It would be set in the config but I can't find for the life of me what line I need to put in the '.markdownlint.jsonc'. I'm sorry I could not parse that out from the links provided.

Would you be able to provide the snippet I need for the config to point to my custom JS. Thanks again.

**Comment by DavidAnson** [comment]
I can't do that easily from my phone, but note that there are TWO different configuration formats. We are suggesting this one (note "-cli2" in the file name): https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-jsonc-example/.markdownlint-cli2.jsonc
