### ISSUE TITLE
Consider adding a command-line parameter to specify the root config file path

### ISSUE THREAD

**Issue by marklester** [DavidAnson/markdownlint-cli2#8]
Can you make it so that this can be given a location where the config is.

The example use case is for ci.
given directory structure

```
.gitlab
markdown-folder
```

When I create a stage I can specify a image with this cli installed
so the config for this would be in the .gitlab folder
currently I could do:
```yaml
script:
  - cd .gitlab/configfolder
  - markdownlint-cli2 ../../**
```
but I would prefer

```yaml
script:
  - markdownlint-cli2  -c .gitlab/configfolder/conf.yml **
```

**Comment by DavidAnson** [comment]
- CLI2 explicitly reserves command line arguments for glob patterns, so I do not see how this could be done without changing that. Also, it adds code/complexity to support something that is already possible (your first example). Is there a technical reason to prefer the second form, or is this more a matter of preference?

**Comment by marklester** [comment]
preference and it also allows more options on how to use this cli. By relying on convention for where the config is it makes devs might have to go through more hoops to make it work in their code bases.

**Comment by DavidAnson** [comment]
I'll leave this open for now for possible feedback, but it is counter to a principle of the tool and I do not expect to implement it.

**Comment by dgroomes** [comment]
Hi, I just wanted to share some feedback because it was requested in this earlier comment:

> I'll leave this open for now for possible feedback, but it is counter to a principle of the tool and I do not expect to implement it.

I'm just getting started with markdownlint and [I've made my own custom lint rule](https://github.com/dgroomes/markdownlint-playground/tree/046274f62ae21ecf76d8fce5f67041f8b6cde8a6). Awesome tool by the way, so featureful and well documented. Thank you 👍 

Now, I'm trying to figure out how I will run the linter as I go about my day-to-day development. So, I've looked into the two CLIs (markdownlint-cli and markdownlint-cli2). My plan is to run the linter manually, in an ad hoc way, when I feel like it. My plan is to not commit a markdownlint-cli2 config file into my "playground" repos because the repos exist to illustrate a point, and so the more boilerplate items (config files, CI files, boilerplate documentation files, etc) is inside of them, the more out of focus they become.

So I think I'll use markdownlint-cli instead, which from what I understand is [equally well endorsed](https://dlaa.me/blog/post/markdownlintcli2)!

This GitHub issue was the piece that made it clear I should probably start with markdownlint-cli and maybe in the future graduate to markdownlint-cli2. Anyway I thought this might be useful feedback from a new markdownlint user even though I don't know what the moral of the story is. Thanks,

**Comment by dgroomes** [comment]
Very cool 👍 !

I've now moved to `markdownlint-cli2` (from `markdownlint-cli`) and am using the new `markdownlint-cli2-config` command: [diff](https://github.com/dgroomes/my-config/compare/a9ab4d145826dc53c423341d4bb3728c8c665afe...9e9ed0d6b37a772b59453216f73f810f4bfcb333).

And now I can use stuff like the pretty formatter, and I'm getting more mileage out of the tools. Works great! I never knew about "clickable links" in the terminal but that works too.

**Comment by DavidAnson** [comment]
Glad to hear it, welcome to the future! :)

FYI, now that it is JSONC, this simulated comment can become a real one: https://github.com/dgroomes/my-config/blob/9e9ed0d6b37a772b59453216f73f810f4bfcb333/markdownlint/.markdownlint-cli2.jsonc#L18

**Comment by DavidAnson** [comment]
Another thing to consider, instead of naming the rules like MD123, you can use the text name like "line-length" which is a little more descriptive and might avoid the need to describe each rule in the list with a comment.

**Comment by dgroomes** [comment]
Very cool, thanks for the tip and code review! I was probably thinking I would memorize the markdown lint rules numbers or something but that's silly. I'll opt for the titled/named rules instead of the `MD...` names!
