### ISSUE TITLE
Suggestion: move to original project

### ISSUE THREAD

**Issue by karolis-sh** [DavidAnson/markdownlint-cli2#9]
As an everyday user of this nice linter, I wanted to ask,  wouldn't it make more sense to have this utility baked-in the main https://github.com/DavidAnson/markdownlint project? I feel that having `markdownlint-cli` and `markdownlint-cli2` is a bit confusing, and having a single official CLI would benefit the community the most.

Anyway, thanks for your effort! ;)

**Comment by DavidAnson** [comment]
Thank you for the kind words! I am part of the way through writing a blog post to explain why I created CLI2. That should answer your questions in more detail. But briefly right now, there are two parts to your question...

The first is about bundling a CLI with the library and that is something I specifically do not want to do because it will bring along a bunch of dependencies that are not needed by users of the library. The library has only ever had one dependency (the parser) and my goal is to keep it that way. Even trying to be conservative about dependencies, CLI2 has 7 of them - and the original CLI has 14! This pattern of having a separate CLI is fairly common among tools like this.

The second question is about replacing the original CLI. As I say in the blog post, that is not a goal. It is a fine tool and it is used by many different projects. Furthermore, CLI2 make some unusual design decisions that not everybody will like. I don't want to force that on anybody, but at the same time I've designed CLI2 to support functionality that has been requested of CLI but not implemented due to the challenges of architecture and compatibility.

**Comment by karolis-sh** [comment]
Regards the number of dependencies, you could have a monorepo structure and simply re-export the CLI as the `bin` utility. Then the main `markdownlint` project would have a single extra `markdownlint-cli2` dependency and still have a clean main project codebase.

Ideally, I'd imagine something like a `prettier` experience - install one dependency and have all the tools to work with main functionality. But yeah, maybe when CLI2 matures, then it would be better to discuss such actions.

**Comment by DavidAnson** [comment]
Here's the post with more context on CLI2: https://dlaa.me/blog/post/markdownlintcli2
