### ISSUE TITLE
GitLab Code Quality report artifact formatter

### ISSUE THREAD

**Issue by mschoettle** [DavidAnson/markdownlint-cli2#92]
Thanks for this nice utility!

I started playing around with it to integrate it into our pre-commit and our GitLab CI pipeline.

As a result, I ended up writing a custom formatter that generates the required code quality report artifact (see [docs](https://docs.gitlab.com/15.4/ee/ci/testing/code_quality.html#implementing-a-custom-tool)) so that any issues show up in the merge request and the diff.

Instead of leaving this buried in a private repo (or publishing it separately), would there be any interest in integrating this into this repo?

**Comment by DavidAnson** [comment]
Sure! Can you point to the code so I can get an idea of the scope of it?

**Comment by mschoettle** [comment]
Here it is: https://github.com/mschoettle/markdownlint-cli2/commit/6bf34774d98a45db4f7b3c7675930c016ff7db3f

**Comment by DavidAnson** [comment]
This looks very reasonable! I will have some questions/feedback, but not too much. Happy to see a PR. Please review CONTRIBUTING.md first. Thanks!!

**Comment by DavidAnson** [comment]
One thing I’d like to clarify before you do any work here: if this gets merged into the CLI2 project, I will treat it as my responsibility/problem and publish updates along with the other packages which will happen under my NPM account. I absolutely understand if you want to maintain more control/visibility over your work, and if so I think you should publish it directly. I’m happy to help with that. Otherwise, I would leave the author field pointing to you, and I would be happy to take patches and updates in the future, but I will assume I might never see you again and handle things accordingly. I hope that’s clear and make sense – I’m happy to chat more if you have concerns.

**Comment by mschoettle** [comment]
Thanks for being clear about this. I think that makes a lot of sense. Given the small size of this formatter I feel it would be a big maintenance overhead to publish it separately. But I also understand if you don't want to start collecting a lot of different formatters in your project.

I am working on a PR and might have a few open issues left where I need some help that I will list in the PR.

**Comment by DavidAnson** [comment]
Sounds good! I'm happy to have formatters in this repo because it's easier to do testing, but wanted to be sure there weren't any surprises. Regarding your PR, I will eventually want a README and integration with tests, but I'm also OK accepting your change without that and adding it myself later.
